# version: '3.8'

# services:
#   app:
#     build: .
#     ports:
#       - "5000:5000"
#     environment:
#       - MYSQL_HOST=db
#       - MYSQL_USER=root
#       - MYSQL_PASSWORD=example
#       - MYSQL_DB=testdb
#     depends_on:
#       - db

#   db:
#     image: mysql:5.7
#     restart: always
#     environment:
#       MYSQL_ROOT_PASSWORD: example
#       MYSQL_DATABASE: testdb
#     ports:
#       - "3308:3306"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-gif-app
    ports:
      - "5000:5000"
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: mysql:5.7
    container_name: docker-gif-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    ports:
      - "3308:3306"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

