# שלב בסיסי - בחירת תמונת בסיס
FROM python

# הגדרת ספריית העבודה בתוך הקונטיינר
WORKDIR /bitcoin_price

# העתקת הקבצים מהפרויקט המקומי לתוך הקונטיינר
COPY requirements.txt requirements.txt
COPY bitcoin_price.py bitcoin_price.py

# התקנת התלויות
RUN pip install --no-cache-dir -r requirements.txt

# חשיפת פורט 5000 בקונטיינר
EXPOSE 5000

# הפקודה שתופעל כאשר הקונטיינר ירוץ
CMD ["python", "bitcoin_price.py"]
